### ISSUE TITLE
Please make it available on ipadOS/iOS theres already an app for safari

### ISSUE THREAD

**Issue by Nag-rigat** [Moustachauve/cookie-editor#102]
This is a big help for us please dev make it available on ipadOS/iOS

**Comment by Moustachauve** [comment]
Publishing an extension for Safari costs $100 USD per year (recurring fee). 

Since Cookie-Editor is a free software and I do not receive any money from it and donations are extremely rare, I can't afford to pay for it for now.

This could change later if I start getting some donations or if my situation allows for this expense.

I'm really sorry. I'd love to make Cookie-Editor available for Safari.
