### ISSUE TITLE
Please add localStorage viewing/editing/deleting.

### ISSUE THREAD

**Issue by gremlinisnotavailable** [Moustachauve/cookie-editor#124]
Many sites use browser localStorage to store state information and other cookie-like information. It would be a fine fit to include such information in this extension's popup window.

Opening my browser's devtools any time I want to clear localStorage is a (minor) pain, and if possible I want to avoid it.

If there is another extension available for Firefox that already does this, let me know.

**Comment by Moustachauve** [comment]
Do you think it would make more sense to have a separate version of this extension that handles localstorage but has a similar interface?

**Comment by Moustachauve** [comment]
I'll close this for now as it is not 100% related to Cookie-Editor, but it is in my backplate to create a new extension for this.

**Comment by powellnorma** [comment]
Personally, I feel having it in the same extension would be more useful in many cases. Because often times, the end user probably would like to export the "entire session", which includes all types of storage.

I see this extension focuses on cookies, and refactoring the UI etc. might be burdensome.
However, maybe the new addon could have a focus on this "export / import everything" instead of "just local storage". So one just clicks "export" and it downloads e.g. a json file (that contains all cookies, local storage, and perhaps more). And can later import it.

AFAIK, an extension with this capability does not currently exist.
