### ISSUE TITLE
No permission to view cookies for page on Android

### ISSUE THREAD

**Issue by Lunairayz** [Moustachauve/cookie-editor#136]
Clicked both buttons, nothing happens. Tried readding, same issue.

![Screenshot_20231010_110533_Firefox Nightly](https://github.com/Moustachauve/cookie-editor/assets/45308130/6fc8e77a-c5d1-4ade-8915-392192f683c3)

**Comment by Moustachauve** [comment]
Kiwi browser is not supported. See #132 for a workaround

**Comment by Lunairayz** [comment]
> Kiwi browser is not supported. See #132 for a workaround

It's Firefox Nightly, my bad, should've specified.

**Comment by Moustachauve** [comment]
@Lunairayz Which version of Firefox nightly are you using?
I will be deploying a new update in a few days that should fix this issue as long as you are on Firefox 120 or above.

**Comment by Lunairayz** [comment]
I was on 119 since 120 released 2 days ago.

**Comment by Moustachauve** [comment]
Yeah this bug is caused by two things:
1) there was a bug in my code that didn't work well with firefox (fixed in https://github.com/Moustachauve/cookie-editor/commit/c2a79a61058f326b405913ba8775b105f90a816e)
2) A bug in firefox that didn't allow for permission popup that got fixed in 120 (https://bugzilla.mozilla.org/show_bug.cgi?id=1810047)

**Comment by shawon370** [comment]
Did you find any solution  to it bro??

**Comment by Moustachauve** [comment]
Now that Firefox 120 is out for a while, there shouldn't be any issues. Feel free to reopen if it still doesn't work for you.
