### ISSUE TITLE
Latest version on Firefox has ads.

### ISSUE THREAD

**Issue by MrGoatsy** [Moustachauve/cookie-editor#137]
Please remove, thanks.

**Comment by Moustachauve** [comment]
Yes, I added ads to all browsers. This is the least intrusive way I found to try to monetize the time I put on this extension. 
I also have to pay for the apple development license to be able to offer it for Safari.

The ads are local, on your computer only and carefully selected by me. It doesn't collect any data or send any data.
You can dismiss the ads by pressing "Not Interested" and that specific ad won't show up again.

I'm sorry for the inconvenience, but keeping Cookie-Editor up costs me money.
Please feel free to sponsor me on Github if you appreciate Cookie-Editor. I might make an ad free version in the future if this covers my monthly fees (around 20$ only).

https://github.com/sponsors/Moustachauve

**Comment by MrGoatsy** [comment]
Then have ads on Safari, don't bother other people who don't use Apple devices with the ads.

Why do we have to suffer for what other people use?

**Comment by Moustachauve** [comment]
You can dismiss the ads so you don't see them anymore. There are only 6-7 of them. 

I spent hundreds, maybe thousands of hours making Cookie-Editor so that people could enjoy it and improve their workflow. I know it's not ideal but you should be able to afford 6-7 clicks to dismiss them.

Apple is not the main source of expenses. I need to pay to keep the web server online and the domain name.

I'm really sorry this makes you suffer, but I find the way you are requesting this to be quite entitled. I'd appreciate some recognition for the efforts I made in order to be able to allow you to use Cookie-Editor, even though it has a tiny ad sometimes.

**Comment by MrGoatsy** [comment]
Don't think my directness is the same as rudeness.

I hate ads, no matter where they are in.

You claimed to have  carefully selected the ads yourself, yet you advertise a VPN which is known for having a garbage privacy ToS, so you clearly did not do any research about this and you just plonked the ones you could find in your addon.

Nobody is forcing you to have a domain and a server, there are plenty of free options available.

Check out https://dot.tk/ for example.

**Comment by Moustachauve** [comment]
I understand, I don't particularly enjoy ads either. 
Feel free to build your own version of Cookie-Editor without ads if you wish.

**Comment by MrGoatsy** [comment]
Then follow the solutions I provided as a way to keep it ad free.

**Comment by Moustachauve** [comment]
If you give me 20$ per month then I don't need to run ads. You could save the whole world from suffering for only 20$ per month.

**Comment by MrGoatsy** [comment]
Nice joke.

**Comment by Moustachauve** [comment]
I'm serious. I need to pay my bills too. You are not entitled to free products. Hire your own programmer if you need.
