### ISSUE TITLE
(optional?) netscape format export

### ISSUE THREAD

**Issue by WGMaker** [Moustachauve/cookie-editor#17]
With a (legacy) Netscape cookie format for the export , it will be compatible with most other cookie export utils and directly usefull for import in programs like WGet , WebGrabPlus etc. Please!!

**Comment by Moustachauve** [comment]
Sure, this sounds like something that could be added as an improvement.

**Comment by WGMaker** [comment]
Hi, thanks for answering. If you are going to implement it , maybe , as another option, or as separate extension .. make it a full cookie exporter. There is nothing for Edge right now.
FYI : I made a ‘quick & dirty’ Cookie_Edit2Netscape converter in C# . If you are interested, let me know.

regards   Jan

P.S I am the developer of WebGrabPlus as in http://webgrabplus.com/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Moustachauve** [comment]
Hi,

What do you mean by "make it a full cookie exporter"? I was thinking of just adding an option to the format of the export to the current feature. Would you like something more than a new format for the current cookie exporter?

**Comment by WGMaker** [comment]
Hi,

Right now it will only export cookies from the domain it  is actually connected to. What I mean with ‘full’ is not just that domain but all cookies stored locally . Most cookie import functions of the programs I mentioned have options to filter from this complete set for one or more domains. That is important because some http requests rely on cookies not just from their own domain but from one or two extra.

Regards Jan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by iwanchan** [comment]
Hi, I'm user of EditThisCookie and after some searching for firefox version I'm redirected to here. I use name=value pair format in EditThisCookie, in php file_get_contents().
So maybe add this format too as enhancement.

Regards

**Comment by stdedos** [comment]
Hey @Moustachauve!

Is this something still considered for the project?
Are you planning to implement it?

If not, I can try to submit a PR for it (at least the code for it; I am not sure how would the UI work)

**Comment by Moustachauve** [comment]
Hello @stdedos

As you can see, I'm not really actively working on this project recently, but PR are always appreciated. If you do make one, I can take care of the UI part of it. 

I guess either a different button for different format could work if we only have two.
A more flexible way I could implement it is with a dropdown where you select the desired format and it would save the preference for future exports (default selected)

Should Import also support this format?

**Comment by stdedos** [comment]
I have added a small PoC code to my https://github.com/stdedos/cookie-editor/tree/feature/17-cookies-as-netscape branch.

I have isolated the `(export)cookiesAs#` logic, and I've written the counterpart function for the Netscape format (more details in the commit).

The functionality can be of course a drop-down (for additional extensibility).
My original thought was that the original button would be split in two on hover (but that's just flashy for no reason, and also not future-proof).

---- 

> Should Import also support this format?

Theoretically, yes - but I am not entirely sure of feature-parity 😕
I had already to fake the second field:

> **flag** - A TRUE/FALSE value indicating if all machines within a given domain can access the variable. This value is set automatically by the browser, depending on the value you set for domain.

because the logic (in the extension's context) perplexes me.
* `if all machines within a given domain can access the variable`?!?
  Wut does that even mean? If the site has set the cookie then _most likely it can also read it_
* `This value is set automatically by the browser, depending on the value you set for domain.` 🤯 

Others have:
* used `cookie.hostOnly` (https://github.com/rotemdan/ExportCookies/blob/master/popup.js#L73), which I thing is utterly wrong
* hardcoded TRUE (https://github.com/dandv/convert-chrome-cookies-to-netscape-format/blob/master/convert-cookies.js#L29)

---- 

As far as expirationDate goes, I am not sure what to do there exactly either on export.
"Back in the Netscape days", there was no reason to "save" session cookies - you could just keep them in-memory. As such, you didn't have to write them to any file.

Adding any timestamp `<= now()` means that the cookie is immediately discarded. Adding no-value "might be the best"; but what if the parser disqualifies the whole file because of one missing field / wrong line?
Others have:
* used 0 (https://github.com/rotemdan/ExportCookies/blob/master/popup.js#L76), which is problematic (for the reasons described above)
* used "sentinel" value of +1d (https://github.com/dandv/convert-chrome-cookies-to-netscape-format/blob/master/convert-cookies.js#L29), which is best of both worlds - expiration is "short enough" but not too short

**Comment by Moustachauve** [comment]
I'm happy to announce (better late than never) that the next version of Cookie-Editor will support both import and export of netscape format!

Thanks a lot for your help @stdedos, you made it simpler for me to implement this.

**Comment by Moustachauve** [comment]
This version is now available on the Chrome Web Store! It will be available soon but is pending review for Firefox, Opera, Edge and Safari.
