### ISSUE TITLE
Import the cookie but shows "No host permissions for cookies at url: "chrome://newtab/"

### ISSUE THREAD

**Issue by yeqing686** [Moustachauve/cookie-editor#20]
When I import the cookie, but it doesn't work and shows "No host permissions for cookies at url: "chrome://newtab/"

**Comment by Moustachauve** [comment]
Hi, thanks for the report!

Just to make sure since its not well indicated, in order to import cookies, you need to have the website that the cookies will be applied to open in the active tab. 
According to the error message, I am guessing that you are trying to import them when on a new empty tab. Is that correct?
