### ISSUE TITLE
chrome version 84 is not support the svg image?

### ISSUE THREAD

**Issue by stephenmom** [Moustachauve/cookie-editor#34]
I find out that extension is slow on chrome version 84  and I delele all svg html in source code

**Comment by Moustachauve** [comment]
Hi @stephenmom 

Seems like this is an issue in chrome 84 itself and is going to be fixed in a future version. Here are some details on it:
https://bugs.chromium.org/p/chromium/issues/detail?id=1107442&q=svg&can=2
https://stackoverflow.com/questions/63056304/svgs-fail-to-render-on-initial-page-load-in-chrome-84
