### ISSUE TITLE
View cookies from incognito tabs

### ISSUE THREAD

**Issue by stdedos** [Moustachauve/cookie-editor#57]
Is it possible to save cookies from incognito tabs?

The extensions strip button shows me the mainland cookies, and the devtools tab shows me an empty collection.

**Comment by Moustachauve** [comment]
What error are you getting? Did you enable the extension to run in incognito mode?

I assume you are using chrome since you use the term incognito.

Here's how to allow an extension to run in incognito
- Open Incognito window
- Go to chrome://extensions
- Find the extension, click Details
- Toggle the button "Allow in Incognito" to allow the extension to run in incognito mode

**Comment by Moustachauve** [comment]
I can confirm that when using incognito, I will only see the cookies from the non incognito session.

**Comment by gentue** [comment]
Noticed this too, the editor doesn't seem to do anything when in incognito, which is where I use it the most

**Comment by Moustachauve** [comment]
Fixed by #89, will be part of a near future update
